### ISSUE TITLE
userstate available outside of main()

### ISSUE THREAD

**Issue by mickgardner** [xyproto/permissionbolt#2]
Hi there,

Just a quick question (apologies if this is obvious), in the echo example "userstate" is available only inside of main(). How do I make userstate available outside of the main() function, say for example if I have a bunch of handlers funcs separate from the main func?

Michael

**Comment by xyproto** [comment]
Hello Michael,

One way is to use the [pinterface](https://github.com/xyproto/pinterface) package, like in [this source file](https://github.com/xyproto/algernon/blob/master/luahandler.go) (using `perm pinterface.IPermissions` as the argument).

Sincerely,
Alexander F Rødseth

**Comment by mickgardner** [comment]
Thanks Alexander, I'll take a look at pinterface.

Kind regards
Michael Gardner
