### ISSUE TITLE
Database Name and Access

### ISSUE THREAD

**Issue by phrozen** [xyproto/permissionbolt#3]
~~I've read all the code and I found no way to specify the path (or name) for the bolt database.~~ **Edit: Closing issue, I missed the function the first time.** 

Another (unrelated) thing is, you're using your library SimpleBolt for all BoltDB access, but I think there should be a way to expose the SimpleBolt object (I think there is), but should be documented. I'm already using BoltDB on my project and after seeing SimpleBolt I might use that too, but I think there is no point on tracking both database objects. SimpleBolt should also expose the underlying BoltDB object for things like backup and such.

**Comment by xyproto** [comment]
Hi,

Yes, as you found out, you can use the `NewWithConf` function to specify a filename, and the `Database()` function on the userstate struct to retrieve the Bolt database.

Here is a complete example:
https://gist.github.com/xyproto/87d95ea79ad1019d3599

Thanks for checking out permissionbolt.

Cheers!
