### ISSUE TITLE
*UserState missing CookieSecret()

### ISSUE THREAD

**Issue by dudeskeeroo** [xyproto/permissionbolt#5]
Bit of noob, please be kind if I'm messing up here...

I'm vendoring packages using the new **dep** tool and I'm using permissionbolt.

The latest release of **pinterface** (v4.0.0) and HEAD,  introduces a new method to the `pinterface.IUserState` interface, `CookiSecret`.

**permissionbolt** relies on **pinterface** package but does not implement this interface because `UserState` doesn't have a `CookieSecret` method.

If you use the HEAD of permissionbolt and pinterface, or your vendoring tool gets the latest releases of these packages, you end up with a build error like this:

> ../../vendor/github.com/xyproto/permissionbolt/permissionbolt.go:69: cannot use perm.state (type *UserState) as type pinterface.IUserState in return argument:
> 	*UserState does not implement pinterface.IUserState (missing CookieSecret method)

I think I've wangled **dep** to give me v2.0.0 of pinterface and the build now works. But you may want to ensure the HEADs of each project are compatible.

Cheers!

**Comment by xyproto** [comment]
Thanks for reporting, will look into this!

**Comment by xyproto** [comment]
permissionbolt do have a `CookieSecret` method, though:

https://github.com/xyproto/permissionbolt/blob/master/userstate.go#L374

I updated the `2.0` tag in case that helps.

**Comment by dudeskeeroo** [comment]
Thanks for that, it did help.

The old `2.0` tag (`bbbb574`) didn't have the `CookieSecret()` function but the new `2.0` tag revision (`657ad1a`) does.

**For anyone googling  a solution...**
If you have the same issue, use `git fetch --tags` to retrieve the new 2.0 tag on your dev machine's `$GOPATH/src/github/xyproto/permissionbolt` directory... I don't think git fetch grabs altered tags by default. If you aren't using `HEAD` and want to use `2.0` you can issue a `git checkout 2.0` to use the new tag revision which has the `CookieSecret()` method.

And if you're using the dep tool and were pinning to 2.0, issue a `dep ensure --update github.com/xyproto/permissionbolt` to get the new 2.0 tag in your vendor dir (and Gopkg.lock will be updated to reflect this).

**Comment by xyproto** [comment]
Dependency handling can be cumbersome. I'm glad it worked out. For the next release (and a new 2.1 or 3.0 tag), adding permissionbolt to dependency managers will hopefully be smoother.
