### ISSUE TITLE
Get all fields for a user

### ISSUE THREAD

**Issue by therealjoesmith** [xyproto/permissionbolt#6]
Hello

I'm looking to list all fields stored for a user. Any way to access the data without knowing the keys? I think it will be like the state.users.Get(username, <key>) function, but take only a username as the argument and return a map of key:value pairs.

Thanks!

**Comment by xyproto** [comment]
Retrieving the keys is possible without any modifications to [simplebolt](https://github.com/xyproto/simplebolt) or [permissionbolt](https://github.com/xyproto/permissionbolt).

However, it's not completely straightforward, and should probably be added as a feature to `simplebolt` and/or `permissionbolt`.

```go
// GetDB retrieves the underlying Bolt database from the permissionbolt.UserState
func GetDB(userstate *permissionbolt.UserState) *bolt.DB {
	return (*bolt.DB)(userstate.Database())
}

// GetProps retrieves the properties for a given username
func GetProps(db *bolt.DB, username string) ([]string, error) {
	var props []string
	return props, (*bolt.DB)(db).View(func(tx *bolt.Tx) error {
		bucket := tx.Bucket([]byte("users"))
		if bucket == nil {
			return simplebolt.ErrBucketNotFound
		}
		// Loop through the keys
		return bucket.ForEach(func(byteKey, _ []byte) error {
			combinedKey := string(byteKey)
			if strings.HasPrefix(combinedKey, username+":") {
				fields := strings.SplitN(combinedKey, ":", 2)
				props = append(props, string(fields[1]))
			}
			return nil // Continue ForEach
		})
	})
}
```

Here is a full example as a Gist:

https://gist.github.com/xyproto/1e37bdf1e5d07538ff971534b6ac73e1

**Comment by xyproto** [comment]
It is now possible to use `userstate.Properties("bob")` to retrieve a list of properties for that username.
